[project]
name = "weathermcpserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    "fastmcp>=2.14.3",
    "httpx>=0.28.1",
]

[tool.uv]
package = true

[tool.setuptools.packages.find]
where = ["src"]